-- 코드를 입력하세요
SELECT
    rh.HISTORY_ID,
    cc.DAILY_FEE * (DATEDIFF(rh.END_DATE, rh.START_DATE) + 1) * ((100 - IFNULL(dp.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY rh
JOIN CAR_RENTAL_COMPANY_CAR cc ON rh.CAR_ID = cc.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
    ON dp.CAR_TYPE = cc.CAR_TYPE
    AND dp.DURATION_TYPE = CASE
        WHEN DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 >= 7  THEN '7일 이상'
        ELSE NULL
    END
WHERE cc.CAR_TYPE = '트럭'
ORDER BY FEE DESC, rh.HISTORY_ID DESC
