-- 코드를 입력하세요
WITH t1 AS (
    SELECT MEMBER_ID, COUNT(*) AS NUM
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY NUM DESC
    LIMIT 1
)
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW r
JOIN MEMBER_PROFILE m ON m.MEMBER_ID = r.MEMBER_ID
WHERE r.MEMBER_ID = (SELECT MEMBER_ID FROM t1)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;